### ISSUE TITLE
Type error with mdast@6

### ISSUE THREAD

**Issue by Saul-Mirone** [wooorm/remark-inline-links#7] opened 2023-07-09 04:31 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-inline-links@6.0.1

### Steps to reproduce

1. Install latest remark and remark-inline-links.
2. Use the remark-inline-links plugin.
3. Run `tsc` and see the error.

### Expected behavior

Node type error reported.

### Actual behavior

```bash
Type 'Root' is not assignable to type 'Node<Data>'.
           Types of property 'data' are incompatible.
             Type 'import("/Users/mirone/Code/milkdown-repos/milkdown/node_modules/.pnpm/@types+unist@3.0.0/node_modules/@types/unist/index").Data | undefined' is not assignable to type 'import("/Users/mirone/Code/milkdown-repos/milkdown/node_modules/.pnpm/@types+unist@2.0.6/node_modules/@types/unist/index").Data | undefined'.
```

### Runtime

Node v16

### Package manager

pnpm

### OS

macOS

**Comment by remcohaszing** [comment] 2023-07-09 07:30
This issue is caused by `@types/mdast` depending on `@types/unist@*`. Unfortunately DefinitelyTyped uses `*` dependency ranges. This issue exists now that we're in the process of updating all packages in the unified ecosystem.

You can solve the issue using npm resolutions or yarn overrides in `package.json`.

```jsonc
{
  // for npm
  "resolutions": {
    "@types/node": "2"
  },
  // for yarn
  "overrides": {
    "@types/node": "2"
  }
}
```

For pnpm there may be a similar solution, but I'm not sure what. Nite that this is a temporary workaround. The issue should resolve itself later.

**Comment by wooorm** [comment] 2023-07-09 09:23
Hey!

I don‘t think it’s that.

The issue is about `mdast@6` (which does not exist, but presumably refers to @types/mdast@4).
That version does not work with this project. Or most projects.

The solution is to not yet use @types/mdast@4.

If you do use @types/mdast@3, and if that does fail on @types/unist, then the override solution provided by @remcohaszing does the trick. But please note that the code needed is:

```js
{
  // for npm
  "resolutions": {
    "@types/unist": "2"
  },
  // for yarn
  "overrides": {
    "@types/unist": "2"
  }
}
```

Closing because all projects have these problems. And we’re in the process to update everything. It isn’t useful to track it in individual projects.

**Closed as completed by wooorm** 2023-07-09 09:23 UTC
Labels: 👀 no/external, 👎 phase/no
